sudo: required
group: deprecated-2017Q4

services:
  - docker

before_install:
  - env | grep TRAVIS > .env
  - docker pull yaktor/node:0.39.0
  - ./run.sh npm install
  - ./run.sh npm run gen-src

script:
  - ./run.sh npm run ci

after_success:
  - ./run.sh grunt coveralls:ci
  - ./run.sh ./travis-npm-publish.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b3322e3bfdacd5e58db4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
