# This Dockerfile is used to cause a new yaktor/yaktor image to be released
# to match the version of yaktor produced during a CI build.
# See ../.travis.yml after_success & ../update-docker-yaktor.sh.

FROM scispike/node:0.31.0
USER node
VOLUME /yaktor
