version: '2'
services:
  app:
    build:
      context: ./docker
      args:
        USER: docker
    image: ${APP_NAME}:${APP_TAG}
    environment:
      APP_NAME_UPPERCASE_YAKTOR_SERVERS_DEFAULT_AMQP_FORCE: 1
      APP_NAME_UPPERCASE_YAKTOR_SERVERS_DEFAULT_AMQP_OPTIONS_CONNECTION_HOST: ${APP_NAME}-amqp
      APP_NAME_UPPERCASE_YAKTOR_SERVERS_DEFAULT_PORT: 80
      APP_NAME_UPPERCASE_YAKTOR_SERVERS_DEFAULT_MONGO_HOST: ${APP_NAME}-mongo
    depends_on:
      - amqp
      - mongo
    hostname: ${APP_NAME}-app
    container_name: ${APP_NAME}-app
    volumes:
      - ./:/app
      - ~/.npmrc:/home/docker/.npmrc
      - ~/.npm:/home/docker/.npm
    networks:
      default:
        aliases:
          - ${APP_NAME}.yaktor
    working_dir: /app
  amqp:
    hostname: ${APP_NAME}-amqp
    container_name: ${APP_NAME}-amqp
    image: rabbitmq
    networks:
      - default
  mongo:
    hostname: ${APP_NAME}-mongo
    container_name: ${APP_NAME}-mongo
    image: mongo:3.0.4
    networks:
      - default
  dns:
    hostname: ${APP_NAME}-dns
    container_name: ${APP_NAME}-dns
    image: andyshinn/dnsmasq
    dns: 8.8.8.8
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/udp
      - 53:53/tcp
    command: --max-cache-ttl=30 --max-ttl=30
    networks:
      - default
networks:
  default:
    driver: bridge
