version: '2'
services:
  app:
    build:
      context: ./docker
      args:
        USER: docker
    image: ${APP_NAME}:${APP_TAG}
    environment:
      FORCE_AMQP: 1
      AMQP_HOST: ${APP_NAME}-amqp
      PORT: 80
      MONGO_HOST: ${APP_NAME}-mongo
    depends_on:
      - amqp
      - mongo
    hostname: ${APP_NAME}-app
    container_name: ${APP_NAME}-app
    volumes:
      - ./:/app
      - ~/.npmrc:/home/docker/.npmrc
      - ~/.npm:/home/docker/.npm
    networks:
      network:
        aliases:
          - ${APP_NAME}.yaktor
    working_dir: /app
  amqp:
    hostname: ${APP_NAME}-amqp
    container_name: ${APP_NAME}-amqp
    image: rabbitmq
    networks:
      - network
  mongo:
    hostname: ${APP_NAME}-mongo
    container_name: ${APP_NAME}-mongo
    image: mongo:3.0.4
    networks:
      - network
  dns:
    hostname: ${APP_NAME}-dns
    container_name: ${APP_NAME}-dns
    image: andyshinn/dnsmasq
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/udp
      - 53:53/tcp
    command: --max-cache-ttl=30 --max-ttl=30
    networks:
      - network
networks:
  network:
    driver: bridge
