version: '2'
networks:
  default:
    driver: bridge
services:
  app:
    build:
      context: ./docker
    image: ${APP_NAME}:${APP_TAG}
    environment:
      MONGO_HOST: ${APP_NAME}-mongo
      AMQP_FORCE: 1
      AMQP_OPTIONS_CONNECTION_HOST: ${APP_NAME}-amqp
      SERVERS_DEFAULT_HOST_PORT: 80
#      CASSANDRA_ENABLE: 1
#      CASSANDRA_HOSTS: ${APP_NAME}-cassandra
    depends_on:
      - amqp
      - mongo
    hostname: ${APP_NAME}-app
    container_name: ${APP_NAME}-app
    volumes:
      - ./:/app
      - ~/.npmrc:/home/docker/.npmrc
      - ~/.npm:/home/docker/.npm
    networks:
      default:
        aliases:
          - ${APP_NAME}.yaktor
    working_dir: /app
  amqp:
    hostname: ${APP_NAME}-amqp
    container_name: ${APP_NAME}-amqp
    image: rabbitmq
  mongo:
    hostname: ${APP_NAME}-mongo
    container_name: ${APP_NAME}-mongo
    image: mongo:3.0.4
#  cassandra:
#    hostname: ${APP_NAME}-cassandra
#    container_name: ${APP_NAME}-cassandra
#    image: cassandra:2.1
#  dns:
#    hostname: ${APP_NAME}-dns
#    container_name: ${APP_NAME}-dns
#    image: andyshinn/dnsmasq
#    dns: 8.8.8.8
#    cap_add:
#      - NET_ADMIN
#    ports:
#      - 53:53/udp
#      - 53:53/tcp
#    command: --max-cache-ttl=30 --max-ttl=30